# database configuration document

# JDBC / driver
db.driver=org.sqlite.JDBC
db.url=jdbc:sqlite:hotel.db

# hibernate configuration
hibernate.dialect=org.sqlite.hibernate.dialect.SQLiteDialect

# doesn't seem to be working. if models change, delete hotel.db and change to hibernate.hbm2ddl.auto=create
# 'validate' also doesn't seem to work
# using update for now since it allows the project to launch. possibly change to 'none' later
hibernate.hbm2ddl.auto=update

hibernate.show_sql=true
hibernate.format_sql=true
hibernate.use_sql_comments=true

hibernate.connection.pool_size=5
hibernate.temp.use_jdbc_metadata_defaults=false

# logging
org.jboss.logging.provider=slf4j